name: ShellCheck

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - '.github/workflows/shellcheck.yml'
      - '**/*.sh'
  pull_request:
    branches:
      - 'main'
      - 'dev'
    paths:
      - '.github/workflows/shellcheck.yml'
      - '**/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_names: gradlew
          ignore_paths: ./userspace/ksud/src/installer.sh ./.github/scripts/setup-rust-build.sh ./build_private.sh ./vcam/scripts/mode-switch.sh ./vcam/scripts/root-boot.sh ./vcam/scripts/root-manager.sh ./manager/app/src/main/assets/vcam/scripts/mode-switch.sh ./manager/app/src/main/assets/vcam/scripts/root-boot.sh ./manager/app/src/main/assets/vcam/scripts/root-manager.sh
